/*****************************************************************************
 *
 * Project Euler
 * Problem 2
 * 
 * Even Fibonacci numbers
 * 
 * Each new term in the Fibonacci sequence is generated by adding the 
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 * 
 * for The Odin Project
 * by Corey Kazaks
 * ***************************************************************************/

// Declare global starting values
var j = 0; 
var k = 1;
var evenSum = 0;

// Iterate through 4 million and add 
// even numbers to evenSum
for (var i = 1; i <= 4000000; i=(j+k)) {
    if (i % 2 === 0) {
        evenSum+=i;
    }
    j = k;
    k = i;
}

console.log(evenSum);